version: '3'

services:
  websocket-service:
    image: gregszalay/websocket-service:v1.0
    build: .
    command: /app/websocket-service
    volumes:
      - ./credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    env_file:
      - .env
    environment:
      - SERVICE_APP_NAME=device-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
      - DEVICE_SERVICE_HOST=device-service
      - DEVICE_SERVICE_PORT=5000
      - DEVICE_SERVICE_GET_STATION_URL=/chargingstations/station
    ports:
      - "3000:3000"
  device-service:
    image: gregszalay/device-service:v1.0
    build: .
    command: /app/device-service
    volumes:
      - ./credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    env_file:
      - .env
    environment:
      - SERVICE_APP_NAME=websocket-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
    ports:
      - "5000:5000"
  user-service:
    image: gregszalay/user-service:v1.0
    build: .
    command: /app/user-service
    volumes:
      - ./credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    env_file:
      - .env
    environment:
      - SERVICE_APP_NAME=user-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
  transaction-service:
    image: gregszalay/transaction-service:v1.0
    build: .
    command: /app/transaction-service
    volumes:
      - ./credentials/PRIVATE.json:/tmp/keys/PRIVATE.json:ro
    env_file:
      - .env
    environment:
      - SERVICE_APP_NAME=transaction-service
      # LOG_LEVEL Panic, Fatal, Error, Warn, Info, Debug, Trace
      - LOG_LEVEL=Info
